version: '3'

services:
  rpyc_backend:
    build:
      context: ./server
    ports:
      - "18863-18865:18861"

  client:
    build:
      context: ./client
    depends_on:
      - nginx
    network_mode:
      "host"
    deploy:
      replicas: 1

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - rpyc_backend