version: '3'

services:
  rpyc_backend:
    build:
      context: ./server
    ports:
      - "18861-18863:18861"

  client:
    build:
      context: ./client
    depends_on:
      - nginx
    network_mode:
      "host"
    deploy:
      replicas: 1

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rpyc_backend

