version: '3'

services:
  rpyc_backend_1:
    build:
      context: ./server
    environment:
      - PORT=18861
    ports:
      - "18863-18865:18861"

  rpyc_backend_2:
    build:
      context: ./server
    environment:
      - PORT=18862
    ports:
      - "18862:18862"

  rpyc_backend_3:
    build:
      context: ./server
    environment:
      - PORT=18863
    ports:
      - "18863:18863"


  client:
    build:
      context: ./client
    depends_on:
      - nginx
    network_mode:
      "host"
    deploy:
      replicas: 3

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - rpyc_backend_1
      - rpyc_backend_2
      - rpyc_backend_3

  statistics:
    build:
      context: ./statistics
    depends_on:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock