services:
  server:
    build:
      context: ./server
    ports:
      - "18861:18861"

  client:
    build:
      context: ./client
    depends_on:
      - server
    network_mode:
      "host"
    deploy:
      replicas: 100
